Created a github action to build synapse package
Start9Labs/synapse-wrapper pull request #38
Opened 2022-08-08 09:02 UTC by alexjyong

Went and whipped up a github action to build synapse wrapper.  Built out and image, pushed it to my embassy, and it seems to be have installed and ran ok. This will allow you to use github actions to build a package without having to set up a build environment on your local machine. In theory, you should be able to use this framework for other services if you just switch out synapse for whatever.

Also updated the Readme because I found a missing step.

One limitation is that I can't run this in https://github.com/nektos/act locally, which would had been super useful. The rust action at the beginning breaks. Not too sure if it's a bug with my local machine, or with `act` itself. I opened up an issue with them, https://github.com/nektos/act/issues/1295 

Side note, I did update the manifest.yaml temporarily to have the name and id be synapse2 temporarily, but that only seemed to overwrite my current install, and not deploy out a separate service.

2022-08-08 16:46 UTC, alexjyong commented
Ok, currently have an issue with getting the package to run on matrix unfortunately.

I have reached out to @chrisguida and @k0gen about this. Might be something wrong with the build process. 

I am also looking into some tweaks for the current process as well, found a few mistakes in the repo checkouts.

2022-08-08 20:28 UTC, chrisguida commented on .github/workflows/buildService.yml
> +      run: cargo install toml-cli
TOML is actually not used, this can be removed

2022-08-10 15:29 UTC, chrisguida commented
Can you provide a link to the artifact produced by this build?

2022-08-10 15:48 UTC, alexjyong commented
@chrisguida sent you this in the other channel, but I'll post it here as well. 

Last successful build. I believe it was done with the update branch as well: https://github.com/alexjyong/synapse-wrapper/actions/runs/2821775057

This was the github action file used: https://github.com/alexjyong/synapse-wrapper/blob/d39d8e6655de0f767ebea352ab28d0be5dc04ef1/.github/workflows/buildService.yml



Now, the most recent build at the time of writing is this:
https://github.com/alexjyong/synapse-wrapper/runs/7758452172?check_suite_focus=true

Failed with this:

```
embassy-sdk pack
embassy-sdk verify s9pk synapsealt.s9pk
S9PK Validation Error: Contains image for incorrect package: id synapse
make: *** [Makefile:18: verify] Error 24
```
Using this github action code: https://github.com/alexjyong/synapse-wrapper/blob/5a5fe49d4c9b7d8f7aaead27aee34544d929f6c2/.github/workflows/buildService.yml

2022-08-10 15:48 UTC, alexjyong commented
@chrisguida here is the link to the last successful artifact (at the time of writing)
https://github.com/alexjyong/synapse-wrapper/suites/7724169508/artifacts/323636292

2022-08-10 16:51 UTC, alexjyong commented
@chrisguida https://github.com/alexjyong/synapse-wrapper/suites/7755197823/artifacts/325827390 

Newer artifact. No ID changing on this one FWIW.

Code used:
https://github.com/alexjyong/synapse-wrapper/blob/87ae72098b4c5973042cdc6b84d31f8109fcf074/.github/workflows/buildService.yml

2022-08-10 19:30 UTC, chrisguida commented
Is there a way to just zip the s9pk? Don't see why we need all these nested directories:

<img width="195" alt="Screen Shot 2022-08-10 at 2 29 34 PM" src="https://user-images.githubusercontent.com/7445670/184003735-b55880ab-2b8f-4b15-b6bb-cb0ca365aeb6.png">

2022-08-10 19:56 UTC, alexjyong commented
@chrisguida  Yeah, there should be a way. I think that came up from the way I was grabbing the file. I currently have a build job going that might fix it.

2022-08-10 22:18 UTC, alexjyong commented
https://github.com/alexjyong/synapse-wrapper/actions/runs/2835226552

@chrisguida fixed the zip imports issue. 

When will the update branch be merged in? Right now the code is pulling it specifically.

2022-08-11 00:48 UTC, chrisguida commented
It can be merged once @k0gen says it's done, and it gets an approving review

2022-08-11 00:50 UTC, alexjyong commented
@chrisguida right on. Any other feedback with this PR?

2022-08-11 00:53 UTC, chrisguida commented
Not at the moment, it looks great, thanks for putting this together! 

We should probably update it to point at master before merging.

2022-08-11 00:54 UTC, chrisguida commented
And since the build will fail, we should probably hold off on doing that until @k0gen's PR is merged.

2022-08-11 00:54 UTC, alexjyong commented
@chrisguida is master fixed though? I recall there was build issues with master.

2022-08-11 14:21 UTC, alexjyong commented
Merged conflicts fixed at the time of writing. Waiting for build to finish.

2022-08-11 14:49 UTC, alexjyong commented
Successful build https://github.com/alexjyong/synapse-wrapper/runs/7788858117?check_suite_focus=true

@chrisguida if you wanna do a final review

2022-08-11 15:08 UTC, alexjyong commented
Also deleted ElementOnion.dmg @k0gen

2022-08-11 16:11 UTC, chrisguida commented
The artifact is still 1.42

<img width="1341" alt="Screen Shot 2022-08-11 at 11 10 16 AM" src="https://user-images.githubusercontent.com/7445670/184179808-2af902a5-9492-40e5-afea-e2f27a207115.png">

2022-08-11 16:12 UTC, chrisguida requested changes
Please update the title or description with the deletion of the .dmg file

2022-08-11 16:13 UTC, chrisguida commented
@k0gen when you merge this, please please please squash. I don't want 68 commits for this in master

2022-08-11 16:17 UTC, chrisguida commented
@alexjyong If you want to rebase this on master we can test. Otherwise I'm fine with YOLOing this into the S9 fork and fixing after. But the first way is cleaner if you're not 100% sure it will work.

2022-08-11 19:09 UTC, k0gen commented
ok the `master` is officially frozen

2022-08-11 20:43 UTC, chrisguida requested changes
@alexjyong Can you rebase this on master? I promise this is the last time. It's just that there's a bunch of commits now that shouldn't be here

2022-08-12 13:31 UTC, chrisguida commented
@alexjyong Is this PR still needed for anything?

2022-08-12 13:45 UTC, alexjyong commented
@chrisguida it is not. I kept it around until the other one was merged in JIC. Closing this out now.

2022-08-12 13:45 UTC, closed without merging